# Generated by Django 2.2.1 on 2019-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=32, primary_key=True, serialize=False)),
                ('html_url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('login', models.CharField(max_length=100)),
                ('forks_count', models.DecimalField(decimal_places=0, max_digits=16)),
                ('stargazers_count', models.DecimalField(decimal_places=0, max_digits=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='Repo',
            new_name='Topic',
        ),
    ]
